# fly.toml app configuration file generated for debuilder on 2025-01-08T18:07:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'debuilder'
primary_region = 'lhr'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
